# Generated by Django 5.0.2 on 2025-06-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scraped_data',
        ),
        migrations.AddField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.JSONField(default=dict, help_text="User's dietary restrictions and allergies"),
        ),
        migrations.AddField(
            model_name='profile',
            name='meal_plan',
            field=models.JSONField(blank=True, help_text='Generated meal plan and Instacart cart URL', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(default=dict, help_text="User's food preferences and favorite cuisines"),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_store_id',
            field=models.CharField(blank=True, help_text='Preferred Instacart store ID', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weekly grocery budget', max_digits=10, null=True),
        ),
    ]
